
    services:
        server:
            build:
                context: ./server
            image: server-image
            networks:
                - fibonacci-network
                
                
        loadbalancer:
            build:
                context: ./load_balancer
            environment:
                - NUMBER_OF_SERVERS=1
                - LOAD_BALANCER_PORT=8000
                - LOCAL_TIMEOUT=2
                - ELASTICITY_SLEEP=10
                - FAAS_CONTAINER_NAME=redis-container
                - FAAS_FUNCTION_NAME=faas
                - AWS_ACCOUNT_ID=100329557600
                - AWS_ROLE=arn:aws:iam::100329557600:role/LabRole
                - AWS_DEFAULT_REGION=us-east-1
            ports:
                - "8000:8000"
            networks:
                - fibonacci-network
            volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - /faas:/faas
                - C:\Users\danil\.aws\credentials:/root/.aws/credentials:ro

    networks:
        fibonacci-network:
            name: fibonacci-network
    